#ccflags-y += -Wall
	
#ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/msg2836/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/base/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include/
ccflags-y += -I$(srctree)/include/

obj-y += ilitek_drv_main.o \
	ilitek_drv_mp_test.o \
	ilitek_drv_mtk.o \
	ilitek_drv_update.o \
	new_mp_test/mp_misc.o \
	new_mp_test/mp_result.o \
	new_mp_test/mp_parse.o \
	new_mp_test/mp_test.o \
	new_mp_test/mp_main.o \


